### ISSUE TITLE
Grafiko atvaizdavimas

### ISSUE THREAD

**Issue by DarTas1** [lukas-sparnauskas/medziagu-mokslo-projektas#2]
https://www.learnpyqt.com/tutorials/plotting-matplotlib/
reikia nubrėžti tiesinę priklausomybę temperatūros ir ilgio
naudoti graphicsview vietą. galima keisti į kitą kokį nors widgetą pagal tutorialą iš linko. naudoti panašius matmenis
pradiniai duomenys paduodami su slideriais temp1, temp2, lenght1, length2.
atvaizduoti grafiką po truputį užsipildant, o ne iškarto kad pyst ir atsiranda.

**Comment by lukas-sparnauskas** [comment]
kol kas pyst ir atsiranda bet padarysim manau kad po truputį atsiradinėtų

**Comment by lukas-sparnauskas** [comment]
done, padaryta kad palaipsniui atsiranda
