### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by DarTas1** [lukas-sparnauskas/medziagu-mokslo-projektas#3]
Pagal pgr reikavimus (issue) padaryti veikiantį interface
Widgetai panašiai kaip sketch'e savo vietosi.
Gali būti pakitę slideriai (kitokie pradiniai duomenys)
Iš sliderių realtime paimti duomenis ir išvest į atitankamo sliderio qtextbrowser value lauką

**Comment by DarTas1** [comment]
Almost done. Liko iš sliderių paimti duomenis realtime

**Comment by DarTas1** [comment]
https://stackoverflow.com/questions/52918182/how-to-get-value-from-a-qslider

**Comment by lukas-sparnauskas** [comment]
> Almost done. Liko iš sliderių paimti duomenis realtime

Done

**Comment by lukas-sparnauskas** [comment]
Dar pridėt labels reikia reikšmių prie sliderių ir bus baigta

**Comment by lukas-sparnauskas** [comment]
QTextBrowserius pakeičiau į QSpinBox kad būtų galima tik skaičius vesti

**Comment by lukas-sparnauskas** [comment]
Dar kažkur manau reikės pridėti skaičiuojamo koeficiento reikšmę

**Comment by DarTas1** [comment]
DONE
