### ISSUE TITLE
Skaičiavimai

### ISSUE THREAD

**Issue by DarTas1** [lukas-sparnauskas/medziagu-mokslo-projektas#5]
Skaičuot:
alfa
deltaL

Jei Alfa, reikia ilgių ir temperatūrų. medžiagų pasirinkimas turi būt disabled,
Jei galutinis ilgis, tai šis pasirinkimas turi būti išjungtas

**Comment by DarTas1** [comment]
groupbox kur yra atitinkami slideriai ir kiti duomenys įjungimas išjungimas: https://gis.stackexchange.com/questions/201732/enable-groupbox-only-when-checkbox-is-checked-pyqgis

**Comment by lukas-sparnauskas** [comment]
Done

**Comment by DarTas1** [comment]
Jei temperatūrų ir ilgių skirtumai yra abu neigiami, tai reiškia kad objektas buvo šaldomas ir dėl to traukėsi. alfa gaunasi toks pat kaip ir kai abu skirtumai yra teigiami. (alfa skaičiavimas)
Jei pradinė temperatūra yra dedesnė nei galutinė, reiškia, reiškia galutinis ilgis bus mažesnis nei pradinis (L skaičiavimas)
Jei temperatūrų skirtumas teigiamas ir ilgių - neigiamas, arba atvirkščiai, reiškia alfa bus neigiamas (nemanau, kad yra tokia egzistuoja tokia medžiaga)

**Comment by lukas-sparnauskas** [comment]
Pataisyta
