### ISSUE TITLE
Daugiau medžiagų ir papildoma info

### ISSUE THREAD

**Issue by lukas-sparnauskas** [lukas-sparnauskas/medziagu-mokslo-projektas#6]
Reikia pridėt daugiau medžiagų (jaučiu iš šitos nuorados kažkiek paimt: https://www.engineeringtoolbox.com/linear-expansion-coefficients-d_95.html) ir kažkokių info pop-upų dar apie kūrėjus arba apie pačias medžiagas.

**Comment by lukas-sparnauskas** [comment]
Padariau langus. Reikia dabar surinkt info ir sudėt.

**Comment by DarTas1** [comment]
doing that

**Comment by DarTas1** [comment]
Pridėta daugiau medžiagų ir pridėti grubūs medžiagų aprašymai.
Autorių info neliečiau. Reikia pridėti Tautvydo grupę prie jo pavardės. No info on that yet
